package com.eazybyts.crm.enums;

public enum IndustryTypeEnum {
APPLICATION_SERVICE_PROVIDER,
DATA_OR_TELECOM_OEM,
ENTERPRISE_RESOURCE_PLANNING,
GOVERNMENT_OR_MILITARY,
MANAGEMENT_ISV,
MANAGEMENT_SERVICE_PROVIDER,
NETWORK_EQUIPMENT_ENTERPRISE,
NON_MANAGEMENT_ISV,
OPTICAL_NETWORKING,
SERVICE_PROVIDER,
SMALL_OR_MEDIUM_ENTERPRISE,
STORAGE_EQUIPMENT,
STORAGE_SERVICE_PROVIDER,
SYSTEMS_INTEGRATOR,
WIRELESS_INDUSTRY,
FINANCIAL_SERVICES,
EDUCATION,
TECHNOLOGY,
REAL_ESTATE,
CONSULTING,
COMMUNICATIONS,
MANUFACTURING
}
